services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Newageerp\SfUservice\Service\UService:
    arguments: [ ]
  Newageerp\SfUservice\Controller\UController:
    arguments: [ ]
  Newageerp\SfUservice\EventListener\OnFlushEventListener:
    arguments: [ ]
    tags:
      - name: "doctrine.event_listener"
        event: "onFlush"
        priority: 900
        connection: "default"
      - name: "doctrine.event_listener"
        event: "postFlush"
        priority: 900
        connection: "default"